name: "🐞 Bug"
description: "버그 제보"
title: "[BugFix] Refactor Title"
labels: ["bug"]
body:
  - type: input
    attributes:
      label: 💡 관련 이슈번호
      description: 버그와 관련된 이슈번호가 있으면 작성해주세요.
      placeholder: "ex. #1-member_signup"
  - type: textarea
    attributes:
      label: 📄 설명
      description: 버그에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.